import asyncio
import sys
from pathlib import Path

from sqlalchemy import select

sys.path.append(str(Path(__file__).resolve().parents[1]))

from core.database import AsyncSessionLocal, engine
from models.blog import BlogPost
from models.user import User
from services.auth import hash_password


async def get_or_create_user(session, username: str, email: str, password: str, role: str) -> User:
    result = await session.execute(select(User).where(User.username == username))
    user = result.scalar_one_or_none()
    if user:
        return user

    user = User(
        username=username,
        email=email,
        hashed_password=hash_password(password),
        role=role,
    )
    session.add(user)
    await session.flush()
    return user


async def create_demo_posts(session, author_id: int, titles: list[str]) -> int:
    result = await session.execute(select(BlogPost).where(BlogPost.author_id == author_id))
    existing_posts = list(result.scalars().all())
    existing_titles = {post.title for post in existing_posts}

    created = 0
    next_index = len(existing_posts) + 1

    for idx, title in enumerate(titles, start=1):
        if title in existing_titles:
            continue

        session.add(
            BlogPost(
                title=title,
                content=(
                    f"Noi dung demo #{next_index} cho buoi trinh bay. "
                    "This record was generated by scripts/seed_demo.py"
                ),
                author_id=author_id,
            )
        )
        created += 1
        next_index += 1

    return created


async def main() -> None:
    async with AsyncSessionLocal() as session:
        admin = await get_or_create_user(
            session,
            username="admin_demo",
            email="admin_demo@example.com",
            password="Admin123!",
            role="admin",
        )
        user = await get_or_create_user(
            session,
            username="user_demo",
            email="user_demo@example.com",
            password="User123!",
            role="user",
        )

        admin_posts = await create_demo_posts(
            session,
            author_id=admin.id,
            titles=[
                "Welcome Blog",
                "Day 5 Migration Complete",
                "Thiet ke schema users va blog_posts",
                "Alembic migration voi MySQL Workbench",
                "Quan ly environment bang uv",
                "JWT va OAuth2 Password Flow",
                "Role-based access control cho admin",
                "Middleware do thoi gian xu ly",
                "Background task ghi log tao bai viet",
                "Docker compose cho API va MySQL",
            ],
        )
        user_posts = await create_demo_posts(
            session,
            author_id=user.id,
            titles=[
                "Day 6 JWT Auth",
                "Day 7 Docker and Background Tasks",
                "CRUD blog bang SQLAlchemy async",
                "Bao mat endpoint bang Bearer token",
                "Kiem thu nhanh bang Swagger UI",
                "Checklist demo mini project FastAPI",
            ],
        )

        await session.commit()

        total_users = (await session.execute(select(User))).scalars().all()
        total_posts = (await session.execute(select(BlogPost))).scalars().all()

    print("Seed complete")
    print("Users: admin_demo/Admin123!, user_demo/User123!")
    print(f"Posts created: {admin_posts + user_posts}")
    print(f"Current totals -> users: {len(total_users)}, posts: {len(total_posts)}")
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
